SELECT play.GameId,
    GameDate,
    GameType,
    PlayNum,
    Eventmsgtype,
    Season,
    HomeTeamId,
    HomePlayer1Id,
    HomePlayer2Id,
    HomePlayer3Id,
    HomePlayer4Id,
    HomePlayer5Id,
    AwayTeamId,
    AwayPlayer1Id,
    AwayPlayer2Id,
    AwayPlayer3Id,
    AwayPlayer4Id,
    AwayPlayer5Id,
    SecRemainGame,
    Period,
    SecRemainPeriod,
    ScoreMargin,
    HomeOff,
    StartEvent,
    EndEvent,
    HomePlayer1Event,
    HomePlayer2Event,
    HomePlayer3Event,
    HomePlayer4Event,
    HomePlayer5Event,
    AwayPlayer1Event,
    AwayPlayer2Event,
    AwayPlayer3Event,
    AwayPlayer4Event,
    AwayPlayer5Event,
    HomeNumPlayers,
    AwayNumPlayers,
    HomeFouls,
    AwayFouls,
    HomeScore,
    AwayScore,
    PossCount,
    SecSinceLastPlay,
    Eventmsgactiontype,
    PosX,
    PosY,
    ShotDistance,
    ShotAngle
FROM Proc_NBAStats_PlayByPlay play
    LEFT JOIN Proc_Shots shot ON play.GameId = shot.GameId
    AND play.EventNum = shot.Eventnum
    JOIN (
        SELECT GameId,
            GameDate,
            GameType
        FROM Proc_NBAStats_Games
    ) game ON play.GameId = game.GameId
WHERE Season > 2006
ORDER BY GameDate,
    GameId,
    PlayNum;