--' sportradar
SELECT GameId,
    PlayNum,
    Eventmsgtype,
    Season,
    HomeTeamId,
    HomePlayer1Id,
    HomePlayer2Id,
    HomePlayer3Id,
    HomePlayer4Id,
    HomePlayer5Id,
    AwayTeamId,
    AwayPlayer1Id,
    AwayPlayer2Id,
    AwayPlayer3Id,
    AwayPlayer4Id,
    AwayPlayer5Id,
    SecRemainGame,
    Period,
    SecRemainPeriod,
    ScoreMargin,
    HomeOff,
    StartEvent,
    EndEvent,
    HomePlayer1Event,
    HomePlayer2Event,
    HomePlayer3Event,
    HomePlayer4Event,
    HomePlayer5Event,
    AwayPlayer1Event,
    AwayPlayer2Event,
    AwayPlayer3Event,
    AwayPlayer4Event,
    AwayPlayer5Event,
    HomeFouls,
    AwayFouls,
    HomeScore,
    AwayScore,
    PossCount,
    SecSinceLastPlay,
    Eventmsgactiontype
FROM Proc_NBAStats_PlayByPlay
WHERE Season = 2020
    AND HomeNumPlayers = 5
    AND AwayNumPlayers = 5
    AND GameId = 22000001;
